//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 VideoCommunication.rc 使用
//
#define IDD_VIDEOCOMMUNICATON_DIALOG    3935
#define IDC_EDIT_VIDEOCOMMUNICATION_ROOMID 3936
#define IDC_LIST_VIDEOCOMMUNICATION_LOG_LIST 3937
#define IDC_MFCLINK1                    3939
#define IDC_BUTTON_VIDEOCOMMUNICATION_LOGOUT 3940
#define IDC_STATIC_VIDEO_COMMUNICATION_1 3941
#define IDC_STATIC_VIDEO_COMMUNICATION_2 3942
#define IDC_STATIC_VIDEO_COMMUNICATION_3 3943
#define IDC_STATIC_VIDEO_COMMUNICATION_4 3944
#define IDC_STATIC_VIDEO_COMMUNICATION_5 3945
#define IDC_STATIC_VIDEO_COMMUNICATION_6 3946
#define IDC_STATIC_VIDEO_COMMUNICATION_7 3947
#define IDC_STATIC_VIDEO_COMMUNICATION_8 3948
#define IDC_STATIC_VIDEO_COMMUNICATION_9 3949
#define IDC_STATIC_VIDEO_COMMUNICATION_10 3950
#define IDC_STATIC_VIDEO_COMMUNICATION_11 3951
#define IDC_STATIC_VIDEO_COMMUNICATION_12 3952

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1745
#define _APS_NEXT_COMMAND_VALUE         5434
#define _APS_NEXT_CONTROL_VALUE         3953
#define _APS_NEXT_SYMED_VALUE           36188
#endif
#endif
