//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 MixStream.rc 使用
//
#define IDD_DIALOG1                     1950
#define IDD_MIXSTREAM_BASIC_CONFIG      1950
#define IDD_DIALOG_MIXSTREAM_ADVANCE_CONFIG 1953
#define IDD_DIALOG2                     1955
#define IDD_DIALOG_MIXSTREAM_ROOMLIST_DLG 1955
#define IDD_MIXSTREAM_DIALOG            4160
#define IDD_MIXSTREAM_PUBLISH           4161
#define IDC_MIX_STREAM_ROOM_ID          5634
#define IDC_STREAM_ID                   5635
#define IDC_MIXSTREAM_STREAMID          5636
#define IDC_MIX_ADVANCE_CONFIG          5638
#define IDC_MFCLINK1                    5639
#define IDC_COMBO_MIXSTREAM_OUTPUT_RESOLUTION 5640
#define IDC_COMBO_MIXSTREAM_OUTPUT_FPS  5641
#define IDC_COMBO_MIXSTREAM_OUTPUT_FRAMERATE 5642
#define IDC_CHECK_CHANNEL_TYPE          5643
#define IDC_CHECK_SOUND_FLAG            5644
#define IDC_MIX_PUBLISH_JOINLIVE        5645
#define IDC_MIX_PUBLISH_LOGOUT          5646
#define IDC_MIXSTREAM_PUBLISH_LOG       5652
#define IDC_MIXSTREAM_                  5653
#define IDC_MIXSTREAM_LOCAL_VIDEO       5653
#define IDC_MIXSTREAM_VIDEO             5653
#define IDC_MIXSTREAM_VIDEO1            5653
#define IDC_MIXSTREAM_VIDEO2            5654
#define IDC_MIXSTREAM_PANNEL            5656
#define IDC_MIXSTREAM_PUBLISH_MIXSTREAM_ID 5663
#define IDC_MIXSTREAM_PUBLISH_ANCHOR_SOUND_VALUE 5664
#define IDC_MIXSTREAM_JOINER_SOUND_VALUE 5665
#define IDC_BUTTON_MIX_STREAM_ADVANCE_CONFIG 5666
#define IDC_MIXSTREAM_ROOMLIST          5667

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1958
#define _APS_NEXT_COMMAND_VALUE         36388
#define _APS_NEXT_CONTROL_VALUE         5668
#define _APS_NEXT_SYMED_VALUE           4162
#endif
#endif
